---
- name: Ensures /root/install/ dir exists
  file: 
    path: /root/install
    state: directory

- name: Ensures /root/install/tls dir exists
  file: 
    path: /root/install/tls
    state: directory

- name: Copy all yaml files
  synchronize:
    src: kube-yaml/
    dest: /root/install/

- name: create self signed certificate for https access
  shell: |
    openssl req -x509 \
    -newkey rsa:2048 \
    -keyout /root/install/tls/kube.loc.key \
    -out /root/install/tls/kube.loc.crt \
    -days 365000 \
    -nodes \
    -subj "/CN=*.kube.loc"
  args:
    creates: /root/install/tls/kube.loc.key


#ingress 
- name: Create ingress controller namespace
  shell: kubectl apply -f /root/install/ingress-nginx-ns.yml

- name: create self signed certificate in kube
  shell: |
    kubectl create secret tls ingress-nginx-tls  --key="/root/install/tls/kube.loc.key"   --cert="/root/install/tls/kube.loc.crt" -n ingress-nginx  --dry-run=true -o yaml | kubectl apply -f -

- name: install ingress controller
  shell: kubectl apply -f /root/install/ingress-nginx-daemonset.yml

#dashboard

- name: Create dashboard namespace
  shell: kubectl apply -f /root/install/kubernetes-dashboard-ns.yml

- name: create self signed certificate for dashboard
  shell: |
    kubectl create secret generic kubernetes-dashboard-certs --from-file=/root/install/tls/ -n kubernetes-dashboard --dry-run=true -o yaml | kubectl apply -f -

- name: install dashboard 
  shell: |
    kubectl apply -f /root/install/kubernetes-dashboard.yml


#Install keycloak
- name: Create keycloak namespace
  shell: kubectl apply -f /root/install/keycloak-ns.yml

- name: create self signed certificate for keycloak
  shell: |
    kubectl create secret generic  keycloak-tls --from-file=/root/install/tls/ -n keycloak --dry-run=true -o yaml | kubectl apply -f -

- name: Install keycloak 
  shell: kubectl apply -f /root/install/keycloak.yml

# Create
- name: Apply pull secrets
  shell: | 
    kubectl create ns {{ item }}  --dry-run=true -o yaml | kubectl apply -f -
  loop: "{{ initial_app_namespaces }}"
    
# Pull secrets
- name: Copy pull secrets
  copy:
    src: kube-pullsecrets/
    dest: /root/install/

- name: Apply pull secrets
  shell: | 
    kubectl apply -f /root/install/kube-pull-secret.yaml -n {{item}}
    kubectl patch serviceaccount default -p '{"imagePullSecrets": [{"name": "kube-pull-secret"}]}' -n {{item}}
  loop: "{{ initial_app_namespaces }}"


# Install Strimzi Operator
- name: Deploy Strimzi Operator
  shell: |
    kubectl apply -f /root/install/kafka-ns.yml
    sed -i 's/namespace: .*/namespace: kafka/' /root/install/strimzi-kafka/install/cluster-operator/*RoleBinding*.yaml
    kubectl create -f /root/install/strimzi-kafka/install/cluster-operator/ -n kafka
    kubectl replace -f /root/install/strimzi-kafka/install/cluster-operator/ -n kafka
    kubectl create secret generic  kafka-tls --from-file=/root/install/tls/ -n kafka --dry-run=true -o yaml | kubectl apply -f -


#create cluster admin user

- name: cluster admin user creation
  shell: |
    kubectl apply -f /root/install/kube-admin-user.yml

- name: get admin user token
  shell: |
    kubectl -n kube-system describe secret $(kubectl -n kube-system get secret | grep kubeadm | awk '{print $1}')
  register: token

- name: print token
  debug: 
    var: token.stdout_lines
