## traefik.yml

# Docker configuration backend
providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.asus.lan`)"

# API and dashboard configuration
api:
  insecure: true

log:
  level: DEBUG