---
- set_fact:
    appname: bqueue

- name: Create {{appname}} folders
  become: true
  file:
    path: /home/{{ ansible_user }}/apps/{{appname}}/data
    state: directory
    owner: "1001"
    group: "{{ ansible_user }}"
    mode: '0755'


- name: Create {{appname}} labels's dictionary
  set_fact:
      traefiklbl: "{{ traefiklbl | default({}) | combine ({ item.key : item.value }) }}"
  with_items:
    - { key: "traefik.http.routers.{{appname}}.entrypoints" , value: 'http'}
    - { key: "traefik.http.routers.{{appname}}.tls" , value: 'false'}
    - { key: "traefik.http.routers.{{appname}}.rule", value: "Host(`{{appname}}.{{ansible_hostname}}.lan`)"}
    - { key: "traefik.http.routers.{{appname}}.service", value : "{{appname}}"}

- name: "Manage {{appname}} container state - {{appstate}} - {{ips[appname]}}"
  docker_container:
    name: "{{appname}}"
    image: registry.hpel.lan/bqueue:latest
    state: "{{appstate}}"
    recreate: "{{recreate}}"
    restart_policy: unless-stopped
    env:
      QUARKUS_ARTEMIS_URL: "tcp://amqbroker.hpel.lan:443?consumerWindowSize=0&sslEnabled=true&trustAll=true"
      BLENDERQUEUE_HOSTNAME: "{{ansible_hostname}}"
    labels: "{{traefiklbl}}"
    volumes:
      - "/home/{{ansible_user}}/apps/{{appname}}/data:/deployments/data:rw"
    networks_cli_compatible: yes
    networks:
      - name: primenet
        ipv4_address: "{{ips[appname]}}"