---
- set_fact:
    appname: amqbroker

- name: Create {{appname}} folders
  become: true
  file:
    path: /home/{{ ansible_user }}/apps/{{appname}}/data
    state: directory
    owner: "185"
    group: "{{ ansible_user }}"
    mode: '0755'


- name: "Manage {{appname}} container state - {{appstate}} - {{ips[appname]}}"
  docker_container:
    name: "{{appname}}"
    image: registry.hpel.lan/amq-broker:7.8.3
    state: "{{appstate}}"
    restart_policy: unless-stopped
    container_default_behavior: no_defaults
    detach: true
    env:
      AMQ_USER: admin
      AMQ_PASSWORD: password
      AMQ_ROLE: admin
      AMQ_REQUIRE_LOGIN: "false"
      AMQ_ENABLE_METRICS_PLUGIN: "true"
      AMQ_JOURNAL_TYPE: "nio"
      AMQ_DATA_DIR: /amqdata
    labels: |
      {
        "traefik.tcp.services.{{appname}}.loadbalancer.server.port": "61616",
        "traefik.tcp.routers.{{appname}}.entrypoints": "https",
        "traefik.tcp.routers.{{appname}}.tls": "true",
        "traefik.tcp.routers.{{appname}}.rule": "HostSNI(`{{appname}}.{{ansible_hostname}}.lan`)",
        "traefik.tcp.routers.{{appname}}.service": "{{appname}}",
        "traefik.http.services.{{appname}}cons.loadbalancer.server.port": "8161",
        "traefik.http.routers.{{appname}}cons.entrypoints": "http",
        "traefik.http.routers.{{appname}}cons.tls": "false",
        "traefik.http.routers.{{appname}}cons.rule": "Host(`{{appname}}cons.{{ansible_hostname}}.lan`)",
        "traefik.http.routers.{{appname}}cons.service": "{{appname}}cons"
      }
    volumes:
      - "/home/{{ansible_user}}/apps/{{appname}}/data:/amqdata:rw"
    networks_cli_compatible: yes
    network_mode: primenet
    networks:
      - name: primenet
        ipv4_address: "{{ips[appname]}}"