---
- set_fact:
    appname: registry

- name: Create {{appname}} folders
  become: true
  file:
    path: /home/{{ ansible_user }}/apps/{{appname}}/data
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'


- name: Create {{appname}} labels's dictionary
  set_fact:
      traefiklbl: "{{ traefiklbl | default({}) | combine ({ item.key : item.value }) }}"
  with_items:
    - { key: "traefik.http.routers.{{appname}}.entrypoints" , value: 'https'}
    - { key: "traefik.http.routers.{{appname}}.tls" , value: 'true'}
    - { key: "traefik.http.routers.{{appname}}.rule", value: "Host(`{{appname}}.{{ansible_hostname}}.lan`)"}
    - { key: "traefik.http.routers.{{appname}}.service", value : "{{appname}}"}


- name: "Manage {{appname}} container state - {{appstate}} - {{ips[appname]}}"
  docker_container:
    name: "{{appname}}"
    image: registry:latest
    state: "{{appstate}}"
    recreate: "{{recreate}}"
    restart_policy: unless-stopped
    env:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    labels: "{{traefiklbl}}"
    volumes:
      - "/home/{{ansible_user}}/apps/{{appname}}/data:/var/lib/registry:rw"
    networks_cli_compatible: yes
    networks:
      - name: primenet
        ipv4_address: "{{ips[appname]}}"