---
- set_fact:
    appname: amqbroker

- name: Create {{appname}} folders
  become: true
  file:
    path: /home/{{ ansible_user }}/apps/{{appname}}/data
    state: directory
    owner: "185"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Create {{appname}} labels's dictionary
  set_fact:
      traefiklbl: "{{ traefiklbl | default({}) | combine ({ item.key : item.value }) }}"
  with_items:
    - { key: "traefik.tcp.services.{{appname}}.loadbalancer.server.port", value: "61616"}
    - { key: "traefik.tcp.routers.{{appname}}.entrypoints", value: "https"}
    - { key: "traefik.tcp.routers.{{appname}}.tls", value: "true"}
    - { key: "traefik.tcp.routers.{{appname}}.rule", value: "HostSNI(`{{appname}}.{{ansible_hostname}}.lan`)"}
    - { key: "traefik.tcp.routers.{{appname}}.service", value: "{{appname}}"}
    
    - { key: "traefik.http.services.{{appname}}cons.loadbalancer.server.port", value: "8161"}
    - { key: "traefik.http.routers.{{appname}}cons.entrypoints", value: "http"}
    - { key: "traefik.http.routers.{{appname}}cons.tls", value: "false"}
    - { key: "traefik.http.routers.{{appname}}cons.rule", value: "Host(`{{appname}}cons.{{ansible_hostname}}.lan`)"}
    - { key: "traefik.http.routers.{{appname}}cons.service", value: "{{appname}}cons"}

- name: "Manage {{appname}} container state - {{appstate}} - {{ips[appname]}}"
  docker_container:
    name: "{{appname}}"
    image: registry.hpel.lan/amq-broker:7.8.3
    state: "{{appstate}}"
    restart_policy: unless-stopped
    env:
      AMQ_USER: admin
      AMQ_PASSWORD: password
      AMQ_ROLE: admin
      AMQ_REQUIRE_LOGIN: "false"
      AMQ_ENABLE_METRICS_PLUGIN: "true"
      AMQ_JOURNAL_TYPE: "nio"
      AMQ_DATA_DIR: /amqdata
    labels: "{{traefiklbl}}"
    volumes:
      - "/home/{{ansible_user}}/apps/{{appname}}/data:/amqdata:rw"
    networks_cli_compatible: yes
    networks:
      - name: primenet
        ipv4_address: "{{ips[appname]}}"