
- name: Download install app image scripts
  when: '"workstation" in features'
  become: true
  get_url:
    url: https://github.com/alainpham/appp/raw/master/{{ item }}.sh
    dest: /usr/local/bin/{{ item }}
    mode: '0755'
  with_items: 
    - install-appimage
    - uninstall-appimage
    - list-appimage

- name: Create app image folder
  when: '"workstation" in features'
  become: true
  file:
    path: /opt/appimages/{{ item.name }}/
    state: directory
    mode: '0755'
  with_items: "{{ appimages }}"

- name: Download appimages
  when: '"workstation" in features'
  become: true
  get_url: 
    url: "{{ item.url }}"
    dest: /opt/appimages/{{ item.name }}/{{ item.name }}.AppImage
    mode: '0755'
    checksum: "{{ item.hash }}"
  with_items: "{{ appimages }}"

- name: Download icons
  when: '"workstation" in features'
  become: true
  get_url: 
    url: "{{ item.icon }}"
    dest: /opt/appimages/{{ item.name }}/{{ item.name }}.png
  with_items: "{{ appimages }}"

- name: Create shortcuts
  when: '"workstation" in features'
  become: true
  shell: |
    cat > /usr/share/applications/{{ item.name }}.desktop << _EOF_
    [Desktop Entry]
    Encoding=UTF-8
    Type=Application
    Name={{ item.name }}
    Comment={{ item.name }}
    Exec=/opt/appimages/{{ item.name }}/{{ item.name }}.AppImage
    Icon=/opt/appimages/{{ item.name }}/{{ item.name }}.png
    Terminal=false
    _EOF_
  with_items: "{{ appimages }}"