---
# - name: force set ansible distrib$
#   become: true
#   set_fact:
#     # ansible_distribution: "Debian"
#     ansible_distribution_file_parsed: true
#     ansible_distribution_file_path: /etc/os-release
#     ansible_distribution_file_variety: Debian
#     ansible_distribution_major_version: 11
#     ansible_distribution_release: "bullseye"
#     ansible_distribution_version: "11"
#   # when: "ansible_lsb.codename == 'bullseye'"


- name: Reboot
  become: true
  reboot:
    reboot_timeout: 60