apiVersion: apps/v1
kind: Deployment
metadata:
  name: amq7-interconnect-operator  
spec:
  replicas: 1
  selector:
    matchLabels:
      name: qdr-operator
  template:
    metadata:
      labels:
        name: qdr-operator
    spec:
      serviceAccountName: qdr-operator
      containers:
        - name: qdr-operator
          # Replace this with the built image name
          image: registry.redhat.io/amq7/amq-interconnect-operator
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - qdr-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "amq7-interconnect-operator"
