{
 "title": "Camel Dashboard - Context View",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(org_apache_camel_ExchangesCompleted{type=\"context\"},namespace)"
   },
   {
    "name": "context",
    "label": "Camel Context",
    "query": "label_values(org_apache_camel_ExchangesCompleted{type=\"context\",namespace=\"$namespace\"},context)"
   },
   {
    "name": "route",
    "label": "Camel Route",
    "query": "label_values(org_apache_camel_ExchangesCompleted{namespace=\"$namespace\",context=\"$context\",type=\"routes\"},route)"
   },
   {
    "name": "processor",
    "label": "Camel Processor",
    "query": "label_values(org_apache_camel_Processor{namespace=\"$namespace\",context=\"$context\",route=~\"$route\"},processor)"
   }
  ]
 },
 "panels": [
  {
   "title": "Global Stats Camel Context : $context",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Instances",
   "type": "singlestat",
   "description": "Number of parallel instances running",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count by (namespace) (org_apache_camel_ExchangesCompleted{namespace=\"$namespace\",type=\"context\",context=\"$context\"})"
    }
   ]
  },
  {
   "title": "Routes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "topk(1,count by (kubernetes_pod_name) (org_apache_camel_ExchangesCompleted{namespace=\"$namespace\",type=\"routes\",route=~\"$route\"}))"
    }
   ]
  },
  {
   "title": "Processors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "topk(1,count by (kubernetes_pod_name) (org_apache_camel_Processor{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",processor=~\"$processor\"}))"
    }
   ]
  },
  {
   "title": "Consumers Inflight",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(org_apache_camel_InflightExchanges{namespace=\"$namespace\",context=\"$context\",type=\"consumer\"})"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "singlestat",
   "description": "Shows completed exchanges of the camel context",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (org_apache_camel_ExchangesCompleted{namespace=\"$namespace\",context=\"$context\",type=\"context\"})"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "description": "Shows failed exchanges of the camel context",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (org_apache_camel_ExchangesFailed{namespace=\"$namespace\",context=\"$context\",type=\"context\"})"
    }
   ]
  },
  { "title": "Traffic Per Route", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Ex/sec $route",
   "type": "singlestat",
   "description": "Show the numbers of exchanges per second for a camel route",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "repeat": "route",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"}[30s]))"
    }
   ]
  },
  {
   "title": "$route Exchanges/sec - all instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 2, "y": 5 },
   "repeat": "route",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (context) (irate(org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"}[30s]))",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "$route  Exchanges/sec - per instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 5 },
   "repeat": "route",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"}[30s])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Inflight $route",
   "type": "singlestat",
   "description": "Current number of inflight exchanges",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 5 },
   "repeat": "route",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (org_apache_camel_ExchangesInflight{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"})"
    }
   ]
  },
  {
   "title": "$route Inflight  - all instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 5 },
   "repeat": "route",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (context)  (org_apache_camel_ExchangesInflight{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"})",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "$route Inflight  - per instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "repeat": "route",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (org_apache_camel_ExchangesInflight{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"})",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Ex/sec $route",
   "type": "singlestat",
   "description": "Show the numbers of exchanges per second for a camel route",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"}[30s]))"
    }
   ]
  },
  {
   "title": "$route Exchanges/sec - all instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 2, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (context) (irate(org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"}[30s]))",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "$route  Exchanges/sec - per instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"}[30s])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Inflight $route",
   "type": "singlestat",
   "description": "Current number of inflight exchanges",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (org_apache_camel_ExchangesInflight{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"})"
    }
   ]
  },
  {
   "title": "$route Inflight  - all instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (context)  (org_apache_camel_ExchangesInflight{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"})",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "$route Inflight  - per instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (org_apache_camel_ExchangesInflight{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"})",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Ex/sec $route",
   "type": "singlestat",
   "description": "Show the numbers of exchanges per second for a camel route",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"}[30s]))"
    }
   ]
  },
  {
   "title": "$route Exchanges/sec - all instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 2, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (context) (irate(org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"}[30s]))",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "$route  Exchanges/sec - per instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"}[30s])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Inflight $route",
   "type": "singlestat",
   "description": "Current number of inflight exchanges",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (org_apache_camel_ExchangesInflight{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"})"
    }
   ]
  },
  {
   "title": "$route Inflight  - all instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (context)  (org_apache_camel_ExchangesInflight{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"})",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "$route Inflight  - per instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (org_apache_camel_ExchangesInflight{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"})",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Ex/sec $route",
   "type": "singlestat",
   "description": "Show the numbers of exchanges per second for a camel route",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"}[30s]))"
    }
   ]
  },
  {
   "title": "$route Exchanges/sec - all instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 2, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (context) (irate(org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"}[30s]))",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "$route  Exchanges/sec - per instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"}[30s])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Inflight $route",
   "type": "singlestat",
   "description": "Current number of inflight exchanges",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (org_apache_camel_ExchangesInflight{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"})"
    }
   ]
  },
  {
   "title": "$route Inflight  - all instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (context)  (org_apache_camel_ExchangesInflight{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"})",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "$route Inflight  - per instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (org_apache_camel_ExchangesInflight{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"})",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Ex/sec $route",
   "type": "singlestat",
   "description": "Show the numbers of exchanges per second for a camel route",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"}[30s]))"
    }
   ]
  },
  {
   "title": "$route Exchanges/sec - all instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 2, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (context) (irate(org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"}[30s]))",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "$route  Exchanges/sec - per instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"}[30s])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Inflight $route",
   "type": "singlestat",
   "description": "Current number of inflight exchanges",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (org_apache_camel_ExchangesInflight{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"})"
    }
   ]
  },
  {
   "title": "$route Inflight  - all instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (context)  (org_apache_camel_ExchangesInflight{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"})",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "$route Inflight  - per instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (org_apache_camel_ExchangesInflight{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"})",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Ex/sec $route",
   "type": "singlestat",
   "description": "Show the numbers of exchanges per second for a camel route",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 25 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"}[30s]))"
    }
   ]
  },
  {
   "title": "$route Exchanges/sec - all instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 2, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (context) (irate(org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"}[30s]))",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "$route  Exchanges/sec - per instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"}[30s])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Inflight $route",
   "type": "singlestat",
   "description": "Current number of inflight exchanges",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 25 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (org_apache_camel_ExchangesInflight{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"})"
    }
   ]
  },
  {
   "title": "$route Inflight  - all instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (context)  (org_apache_camel_ExchangesInflight{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"})",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "$route Inflight  - per instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (org_apache_camel_ExchangesInflight{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"})",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Execution Times Per Route", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Avg Exec time $route",
   "type": "singlestat",
   "description": "Average execution time for a route",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 30 },
   "repeat": "route",
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum by (route) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}) / sum by (route) (org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}))"
    }
   ]
  },
  {
   "title": "Avg Exec time $route - all instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 30 },
   "repeat": "route",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (route) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}) / sum by (route) (org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}))"
    }
   ]
  },
  {
   "title": "Avg Exec time $route - per instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 30 },
   "repeat": "route",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (route,kubernetes_pod_name) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}) / sum by (route,kubernetes_pod_name) (org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Processor Execution Times - $route",
   "type": "table",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 30 },
   "repeat": "route",
   "targets": [
    {
     "expr": "min by (processor,route) (org_apache_camel_Processor{namespace=\"$namespace\",context=\"$context\",route=\"$route\",type=\"processormappings\",processor=~\"$processor\"}) * on(processor) (sum by (processor) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",context=\"$context\",type=\"processors\",processor=~\"$processor\"}) / sum by (processor) (org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"processors\",processor=~\"$processor\"}))"
    },
    {
     "expr": "min by (processor,route) (org_apache_camel_Processor{namespace=\"$namespace\",context=\"$context\",route=\"$route\",type=\"processormappings\",processor=~\"$processor\"}) * on(processor) (sum by (processor) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",context=\"$context\",type=\"processors\",processor=~\"$processor\"}))"
    },
    {
     "expr": "min by (processor,route) (org_apache_camel_Processor{namespace=\"$namespace\",context=\"$context\",route=\"$route\",type=\"processormappings\",processor=~\"$processor\"}) * on(processor) (sum by (processor) (org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"processors\",processor=~\"$processor\"}))"
    }
   ]
  },
  {
   "title": "Avg Exec time $route",
   "type": "singlestat",
   "description": "Average execution time for a route",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 34 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum by (route) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}) / sum by (route) (org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}))"
    }
   ]
  },
  {
   "title": "Avg Exec time $route - all instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (route) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}) / sum by (route) (org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}))"
    }
   ]
  },
  {
   "title": "Avg Exec time $route - per instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (route,kubernetes_pod_name) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}) / sum by (route,kubernetes_pod_name) (org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Processor Execution Times - $route",
   "type": "table",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 34 },
   "targets": [
    {
     "expr": "min by (processor,route) (org_apache_camel_Processor{namespace=\"$namespace\",context=\"$context\",route=\"$route\",type=\"processormappings\",processor=~\"$processor\"}) * on(processor) (sum by (processor) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",context=\"$context\",type=\"processors\",processor=~\"$processor\"}) / sum by (processor) (org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"processors\",processor=~\"$processor\"}))"
    },
    {
     "expr": "min by (processor,route) (org_apache_camel_Processor{namespace=\"$namespace\",context=\"$context\",route=\"$route\",type=\"processormappings\",processor=~\"$processor\"}) * on(processor) (sum by (processor) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",context=\"$context\",type=\"processors\",processor=~\"$processor\"}))"
    },
    {
     "expr": "min by (processor,route) (org_apache_camel_Processor{namespace=\"$namespace\",context=\"$context\",route=\"$route\",type=\"processormappings\",processor=~\"$processor\"}) * on(processor) (sum by (processor) (org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"processors\",processor=~\"$processor\"}))"
    }
   ]
  },
  {
   "title": "Avg Exec time $route",
   "type": "singlestat",
   "description": "Average execution time for a route",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 38 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum by (route) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}) / sum by (route) (org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}))"
    }
   ]
  },
  {
   "title": "Avg Exec time $route - all instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (route) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}) / sum by (route) (org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}))"
    }
   ]
  },
  {
   "title": "Avg Exec time $route - per instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (route,kubernetes_pod_name) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}) / sum by (route,kubernetes_pod_name) (org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Processor Execution Times - $route",
   "type": "table",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 38 },
   "targets": [
    {
     "expr": "min by (processor,route) (org_apache_camel_Processor{namespace=\"$namespace\",context=\"$context\",route=\"$route\",type=\"processormappings\",processor=~\"$processor\"}) * on(processor) (sum by (processor) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",context=\"$context\",type=\"processors\",processor=~\"$processor\"}) / sum by (processor) (org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"processors\",processor=~\"$processor\"}))"
    },
    {
     "expr": "min by (processor,route) (org_apache_camel_Processor{namespace=\"$namespace\",context=\"$context\",route=\"$route\",type=\"processormappings\",processor=~\"$processor\"}) * on(processor) (sum by (processor) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",context=\"$context\",type=\"processors\",processor=~\"$processor\"}))"
    },
    {
     "expr": "min by (processor,route) (org_apache_camel_Processor{namespace=\"$namespace\",context=\"$context\",route=\"$route\",type=\"processormappings\",processor=~\"$processor\"}) * on(processor) (sum by (processor) (org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"processors\",processor=~\"$processor\"}))"
    }
   ]
  },
  {
   "title": "Avg Exec time $route",
   "type": "singlestat",
   "description": "Average execution time for a route",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 42 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum by (route) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}) / sum by (route) (org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}))"
    }
   ]
  },
  {
   "title": "Avg Exec time $route - all instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (route) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}) / sum by (route) (org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}))"
    }
   ]
  },
  {
   "title": "Avg Exec time $route - per instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (route,kubernetes_pod_name) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}) / sum by (route,kubernetes_pod_name) (org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Processor Execution Times - $route",
   "type": "table",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 42 },
   "targets": [
    {
     "expr": "min by (processor,route) (org_apache_camel_Processor{namespace=\"$namespace\",context=\"$context\",route=\"$route\",type=\"processormappings\",processor=~\"$processor\"}) * on(processor) (sum by (processor) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",context=\"$context\",type=\"processors\",processor=~\"$processor\"}) / sum by (processor) (org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"processors\",processor=~\"$processor\"}))"
    },
    {
     "expr": "min by (processor,route) (org_apache_camel_Processor{namespace=\"$namespace\",context=\"$context\",route=\"$route\",type=\"processormappings\",processor=~\"$processor\"}) * on(processor) (sum by (processor) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",context=\"$context\",type=\"processors\",processor=~\"$processor\"}))"
    },
    {
     "expr": "min by (processor,route) (org_apache_camel_Processor{namespace=\"$namespace\",context=\"$context\",route=\"$route\",type=\"processormappings\",processor=~\"$processor\"}) * on(processor) (sum by (processor) (org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"processors\",processor=~\"$processor\"}))"
    }
   ]
  },
  {
   "title": "Avg Exec time $route",
   "type": "singlestat",
   "description": "Average execution time for a route",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 46 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum by (route) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}) / sum by (route) (org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}))"
    }
   ]
  },
  {
   "title": "Avg Exec time $route - all instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (route) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}) / sum by (route) (org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}))"
    }
   ]
  },
  {
   "title": "Avg Exec time $route - per instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (route,kubernetes_pod_name) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}) / sum by (route,kubernetes_pod_name) (org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Processor Execution Times - $route",
   "type": "table",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 46 },
   "targets": [
    {
     "expr": "min by (processor,route) (org_apache_camel_Processor{namespace=\"$namespace\",context=\"$context\",route=\"$route\",type=\"processormappings\",processor=~\"$processor\"}) * on(processor) (sum by (processor) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",context=\"$context\",type=\"processors\",processor=~\"$processor\"}) / sum by (processor) (org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"processors\",processor=~\"$processor\"}))"
    },
    {
     "expr": "min by (processor,route) (org_apache_camel_Processor{namespace=\"$namespace\",context=\"$context\",route=\"$route\",type=\"processormappings\",processor=~\"$processor\"}) * on(processor) (sum by (processor) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",context=\"$context\",type=\"processors\",processor=~\"$processor\"}))"
    },
    {
     "expr": "min by (processor,route) (org_apache_camel_Processor{namespace=\"$namespace\",context=\"$context\",route=\"$route\",type=\"processormappings\",processor=~\"$processor\"}) * on(processor) (sum by (processor) (org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"processors\",processor=~\"$processor\"}))"
    }
   ]
  },
  {
   "title": "Avg Exec time $route",
   "type": "singlestat",
   "description": "Average execution time for a route",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 50 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum by (route) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}) / sum by (route) (org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}))"
    }
   ]
  },
  {
   "title": "Avg Exec time $route - all instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (route) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}) / sum by (route) (org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}))"
    }
   ]
  },
  {
   "title": "Avg Exec time $route - per instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (route,kubernetes_pod_name) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}) / sum by (route,kubernetes_pod_name) (org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"routes\",route=~\"$route\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Processor Execution Times - $route",
   "type": "table",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 50 },
   "targets": [
    {
     "expr": "min by (processor,route) (org_apache_camel_Processor{namespace=\"$namespace\",context=\"$context\",route=\"$route\",type=\"processormappings\",processor=~\"$processor\"}) * on(processor) (sum by (processor) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",context=\"$context\",type=\"processors\",processor=~\"$processor\"}) / sum by (processor) (org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"processors\",processor=~\"$processor\"}))"
    },
    {
     "expr": "min by (processor,route) (org_apache_camel_Processor{namespace=\"$namespace\",context=\"$context\",route=\"$route\",type=\"processormappings\",processor=~\"$processor\"}) * on(processor) (sum by (processor) (org_apache_camel_TotalProcessingTime{namespace=\"$namespace\",context=\"$context\",type=\"processors\",processor=~\"$processor\"}))"
    },
    {
     "expr": "min by (processor,route) (org_apache_camel_Processor{namespace=\"$namespace\",context=\"$context\",route=\"$route\",type=\"processormappings\",processor=~\"$processor\"}) * on(processor) (sum by (processor) (org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",type=\"processors\",processor=~\"$processor\"}))"
    }
   ]
  }
 ]
}