{
 "title": "Camel Dashboard - Context View",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(org_apache_camel_ExchangesCompleted{type=\"context\"},namespace)"
   },
   {
    "name": "context",
    "label": "Camel Context",
    "query": "label_values(org_apache_camel_ExchangesCompleted{type=\"context\",namespace=\"$namespace\"},context)"
   },
   {
    "name": "route",
    "label": "Camel Route",
    "query": "label_values(org_apache_camel_ExchangesCompleted{namespace=\"$namespace\",context=\"$context\",type=\"routes\"},route)"
   },
   {
    "name": "processor",
    "label": "Camel Processor",
    "query": "label_values(org_apache_camel_Processor{namespace=\"$namespace\",context=\"$context\",route=~\"$route\"},processor)"
   }
  ]
 },
 "panels": [
  {
   "title": "Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count by (kubernetes_pod_name) (org_apache_camel_ExchangesCompleted{namespace=\"$namespace\",type=\"context\",context=\"$context\"})"
    }
   ]
  },
  {
   "title": "Routes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "topk(1,count by (kubernetes_pod_name) (org_apache_camel_ExchangesCompleted{namespace=\"$namespace\",type=\"routes\",route=~\"$route\"}))"
    }
   ]
  },
  {
   "title": "Processors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "topk(1,count by (kubernetes_pod_name) (org_apache_camel_Processor{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",processor=~\"$processor\"}))"
    }
   ]
  },
  {
   "title": "Inflight",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(org_apache_camel_InflightExchanges{namespace=\"$namespace\",context=\"$context\",type=\"consumer\"})"
    }
   ]
  },
  { "title": "Traffic Per Route", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Executions/sec $route",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "repeat": "route",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"}[30s]))"
    }
   ]
  },
  {
   "title": "Executions/sec $route",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"}[30s]))"
    }
   ]
  },
  {
   "title": "Executions/sec $route",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(org_apache_camel_ExchangesTotal{namespace=\"$namespace\",context=\"$context\",route=~\"$route\",type=\"routes\"}[30s]))"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dummy Test",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(org_apache_camel_InflightExchanges{namespace=\"$namespace\",context=\"$context\",type=\"consumer\"})"
      }
     ]
    }
   ]
  }
 ]
}