spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: tls-secret-volume
          secret:
            secretName: ${project.artifactId}-tls-secret
            defaultMode: 420
        - name: prop-secret-volume
          secret:
            secretName: ${project.artifactId}-prop-secret
            defaultMode: 420
      containers:
        - 
          image: ${container.registry.url}/${fabric8.namespace}/${project.artifactId}:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 0.2
              memory: 128Mi
            limits:
              cpu: 2.0
              memory: 512Mi
          env:
          - name: AB_JMX_EXPORTER_CONFIG
            value: "prometheus-config.yml"
          volumeMounts:
            - name: tls-secret-volume
              readOnly: true
              mountPath: /deployments/tls
            - name: prop-secret-volume
              readOnly: true
              mountPath: /deployments/config