---
- name: registry
  hosts:
    - hpel.lan
  vars:
    appstate: started
    recreate: false
  tasks:
    - include_role:
        name: home-lab-role
        tasks_from: app-registry

- name: regui
  hosts:
    - hpel.lan
  vars:
    appstate: started
    recreate: false
  tasks:
    - include_role:
        name: home-lab-role
        tasks_from: app-regui

- name: traefik
  hosts:
    - hppa.lan
    - hpel.lan
    - asus.lan
    - work.lan
    - leol.lan
    - bbee.lan
    # - ampi.lan
  vars:
    appstate: started
    recreate: true
  tasks:
    - include_role:
        name: home-lab-role
        tasks_from: app-traefik

- name: fileserver
  hosts:
    - hpel.lan
  vars:
    appstate: started
    recreate: false
  tasks:
    - include_role:
        name: home-lab-role
        tasks_from: app-fileserver

- name: prometheus
  hosts:
    - asus.lan
  vars:
    appstate: started
    recreate: false
  tasks:
    - include_role:
        name: home-lab-role
        tasks_from: app-prometheus

- name: grafana
  hosts:
    - asus.lan
  vars:
    appstate: started
    recreate: false
  tasks:
    - include_role:
        name: home-lab-role
        tasks_from: app-grafana

- name: loki
  hosts:
    - hpel.lan
  vars:
    appstate: absent
    recreate: false
  tasks:
    - include_role:
        name: home-lab-role
        tasks_from: app-loki

- name: nexus
  hosts:
    - hpel.lan
    - work.lan
  vars:
    appstate: started
    recreate: false
  tasks:
    - include_role:
        name: home-lab-role
        tasks_from: app-nexus