- name: rentman
  hosts:
    - asus.lan
  vars:
    appstate: started
    recreate: false
  tasks:
    - include_role:
        name: home-lab-role
        tasks_from: app-rentman

- name: amqbroker
  hosts:
    - hpel.lan
  vars:
    appstate: started
    recreate: false
  tasks:
    - include_role:
        name: home-lab-role
        tasks_from: app-amqbroker

- name: bqueue
  hosts:
    - work.lan
    - hpel.lan
    - leol.lan
    - hppa.lan
  vars:
    appstate: started
    recreate: false
  tasks:
    - include_role:
        name: home-lab-role
        tasks_from: app-bqueue