---
- name: registry
  hosts:
    - hpel.lan
  vars:
    appstate: absent
    recreate: false
  tasks:
    - include_role:
        name: home-lab-role
        tasks_from: app-registry

- name: regui
  hosts:
    - hpel.lan
  vars:
    appstate: absent
    recreate: false
  tasks:
    - include_role:
        name: home-lab-role
        tasks_from: app-regui

- name: traefik
  hosts:
    - hppa.lan
    - hpel.lan
    - asus.lan
    - alaindeb.lan
  vars:
    appstate: started
    recreate: false
  tasks:
    - include_role:
        name: home-lab-role
        tasks_from: app-traefik


- name: rentman
  hosts:
    - asus.lan
  vars:
    appstate: started
    recreate: false
  tasks:
    - include_role:
        name: home-lab-role
        tasks_from: app-rentman

- name: amqbroker
  hosts:
    - hpel.lan
  vars:
    appstate: started
    recreate: false
  tasks:
    - include_role:
        name: home-lab-role
        tasks_from: app-amqbroker