---
- hosts:
    # - hppa.lan
    - hpel.lan
    # - leol.lan
    # - alaindeb.lan
  vars:
    appstate: absent
    recreate: true
  tasks:
    - include_role:
        name: home-lab-role
        tasks_from: app-fileserver

- hosts:
    # - hppa.lan
    - hpel.lan
    # - leol.lan
    # - alaindeb.lan
  vars:
    appstate: started
    recreate: true
  tasks:
    - include_role:
        name: home-lab-role
        tasks_from: app-fileserver