---
# - name: traefik
#   hosts:
#     - asus.lan
#   vars:
#     appstate: started
#     recreate: false
#   tasks:
#     - include_role:
#         name: home-lab-role
#         tasks_from: app-traefik

# - name: prometheus
#   hosts:
#     - asus.lan
#   vars:
#     appstate: started
#     recreate: true
#   tasks:
#     - include_role:
#         name: home-lab-role
#         tasks_from: app-prometheus

# - name: grafana
#   hosts:
#     - asus.lan
#   vars:
#     appstate: started
#     recreate: true
#   tasks:
#     - include_role:
#         name: home-lab-role
#         tasks_from: app-grafana

- name: teddycast
  hosts:
    - bbee.lan
  vars:
    appstate: started
    recreate: false
  tasks:
    - include_role:
        name: home-lab-role
        tasks_from: app-teddycast