---

# - name: bqueue
#   hosts:
#     - work.lan
#     - hpel.lan
#     - leol.lan
#     - hppa.lan
#   vars:
#     appstate: absent
#     recreate: false
#   tasks:
#     - include_role:
#         name: home-lab-role
#         tasks_from: app-bqueue

# - name: bqueue
#   hosts:
#     - work.lan
#     - hpel.lan
#     - leol.lan
#     - hppa.lan
#   vars:
#     appstate: started
#     recreate: false
#   tasks:
#     - include_role:
#         name: home-lab-role
#         tasks_from: app-bqueue

# - hosts:
#     - leol.lan
#   tasks:
#     - name: install
#       include_role:
#         name: home-lab-role
#         tasks_from: tls-setup

# - name: traefik
#   hosts:
#     - leol.lan
#   vars:
#     appstate: started
#     recreate: false
#   tasks:
#     - include_role:
#         name: home-lab-role
#         tasks_from: app-traefik

# - name: prometheus
#   hosts:
#     - asus.lan
#     - hpel.lan
#   vars:
#     appstate: started
#     recreate: false
#   tasks:
#     - include_role:
#         name: home-lab-role
#         tasks_from: app-prometheus

# - name: registry
#   hosts:
#     - hpel.lan
#   vars:
#     appstate: started
#     recreate: false
#   tasks:
#     - include_role:
#         name: home-lab-role
#         tasks_from: app-registry

# - name: loki
#   hosts:
#     - hpel.lan
#   vars:
#     appstate: absent
#     recreate: false
#   tasks:
#     - include_role:
#         name: home-lab-role
#         tasks_from: app-loki

# - name: registry
#   hosts:
#     - hpel.lan
#   vars:
#     appstate: absent
#     recreate: false
#   tasks:
#     - include_role:
#         name: home-lab-role
#         tasks_from: app-registry

- name: nexus
  hosts:
    - hpel.lan
  vars:
    appstate: started
    recreate: false
  tasks:
    - include_role:
        name: home-lab-role
        tasks_from: app-nexus