---
apiVersion: "apps.openshift.io/v1"
kind: "DeploymentConfig"
metadata:
  labels:
    app: "hornetq-client"
    group: "demo"
  name: "hornetq-client"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    app: "hornetq-client"
    group: "demo"
  strategy:
    rollingParams:
      timeoutSeconds: 3600
    type: "Rolling"
  template:
    metadata:
      labels:
        app: "hornetq-client"
        group: "demo"
    spec:
      containers:
      - env:
        - name: "AMQHOST"
          value: "amq-broker-a-0-svc"
        - name: "AMQPORT"
          value: "5446"
        image: "alainpham/hornetq-client:latest"
        imagePullPolicy: "Always"
        name: "hornetq-client"
        resources:
          limits:
            cpu: "2.0"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "128Mi"
        securityContext:
          privileged: false
        volumeMounts:
        - mountPath: "/deployments/tls"
          name: "tls-secret-volume"
          readOnly: true
      volumes:
      - name: "tls-secret-volume"
        secret:
          defaultMode: 420
          secretName: "hornetq-client-tls-secret"
  triggers:
  - type: "ConfigChange"
---
kind: Secret
apiVersion: v1
metadata:
  name: "hornetq-client-tls-secret"
type: Opaque
data:
  keystore.jks: /u3+7QAAAAIAAAABAAAAAQAJYW1xY2xpZW50AAABd/Bg+64AAAUDMIIE/zAOBgorBgEEASoCEQEBBQAEggTrTapFsa893x58WOWxDorgsVlzxA2VqKtXSYI3S8qL5b/ZkUTQCfqngJXsUEnSXQBBGaGnjt6KbQRcaTgPwitv4z257ynxfeZF13/+ucjQLYQp3zvtNMQ4xezqX5blQUf9vEvam/WrEIDjdUmINEjmkun5tTd8w7vNzbVO9ivV4LUuU96+jgSE/uqCSEqAuhlgtdBWRwaMMdgdI56bvXcwTHMQDuftZRm/pbv4lTkr92HIF6oisZYhJdPC19QPe9wrSNRG+Ai287H9I1ODplOls2522hNCS0XUhON5GvKKuvj1a4av5s18a4FrukThSIUEM/EOZfujGK+303RSXAoNUq4ufNTFPjS4yXgD8zYxVpAW4Ny/sRJrmKXPn9XKyhoBZzlSW3pEymSm/PMr+VefX2mRUAMS9fZsSoYCTyEv8ugjzhE2pnWg7ZWx5kIkChuWwWaC4vCjs1FEN30ThBsfd86PsK5e6Z+yiUOBSCx8z51zutv6MNvRIvqis+p08Ahsg2xra9p4qPtrz2nzzbaMCQTzdtboJgb3j5ZiPdihEQ/CcHHhKmJTlKocMy/MzbcdnOELmO+3QdhTF9E3drYcPdNq6KfHaPY7v00fTheKfZZ1lSc9ixs4SCPBgHn8Q5NtyaHRV1wI+6bLD/m7u3/81ep+8ytsXuUdhMHZHDFzoyP2VJW4VNGRFsf8Lxh9tNKhtmQS0xT6D2yB5roHrR+J23rP9tOzAZ4IWGeREVHnBVXv/6szYm+gV9F+jrJSnWIzGL46bIiNZCWS+cUzp9RoqMhTecqEw8H+IUNwj1a/QZljqK15Tncgprmg5t47/mjqRJnbEqigqMVr9uqzBZ3CpndcJ01eBZ19jV/bpQwI9Gw6gkodsuogUl2N/NBfQBIzBCsMnSmOd085uyNIKF7TFjJOsc/+zS22zIXV1uTgEuBtROdqfYxH9Shjslkk+O9W+NBHStDhciN+EKca4R3k3VOE3Vk2mUuTyhq+HRR2kcjMw0PZpLWe53qP5LfVBajihZ03bRx9WX9BqqPe5voRTMk/ib0Vy1aaJByl/3k8JfiXi6xR83QTfkblh685mqrbe6uQGQvKpYhIikPxiBZC5QrBTyAFgiujAwpFGr76lH4FPeJrp2dnA/aLmOmR8Fj8fAfw1asfJ2f6EvwPDh4pjEz3j+iuXsFAVIRBFJIviV9x0QqbFIFkJ5KLxnn93J2E8/nEyUQeJM46PhEYdEf3SGEXVw+/6eq07COjjHlKVyBnJaOJqJsxtxR2OUYKebOq5/Tu08A1M2aDbolsHsCL9O77St9YME7mbV2NwBRifwUw7pjaAGEl6T4OCvABUo9/FX6RrzQhUPTWoUI5NyndzVOs5TV9NGHIBbW6Y2Hz0ibSoGNCq4g8xGc3cs6ZAXS/M6dhZrd4MgELM7gXQlvaaP7NGxg+QnkoxkVUfJOWiX1f7fd6qcA0ibaRiOWFX3xbeiwlL+P1DdY37gx+2uDn9W6bzmpKdEsEG5fXZ+4IHnz/HlxbgD9qxe7xFW3KTws0C3usehXBS5cbNcOwa3BwHG7jgCwDx4ydsh69RNDbfRUGqWi796tbMSaXUrxTKsGal6X/BJEITW8XTHN78fIr3GTOHPRI1WD6HiR3Qd27g4gUJkm6uf7e2NMNy/p2QnpOQhGDLWkxmmvGsusAAAABAAVYLjUwOQAAAs0wggLJMIIBsaADAgECAgRESY+/MA0GCSqGSIb3DQEBCwUAMBQxEjAQBgNVBAMTCWFtcWNsaWVudDAgFw0yMTAxMjMxNTQwMjhaGA8zMDIwMDUyNjE1NDAyOFowFDESMBAGA1UEAxMJYW1xY2xpZW50MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmEg91cWjSiPMKtdIDSSuALXCvsS+q2ek9Ne5gawG07uB+hwcwtHgf+cQoF1XiKzW/5FzXyLIzNhU98UWtaIj1T0vWQlTH+kAq4ovEsuqFRYfRX6+9ZHEVGCsogqjIVz+TWH2c3Lfbb9ne94pXKLz644+SJsjW4jZvssIG6rXBKla5gnGIExwdntXCr/Jcmx67BNbErtqBR3NEgDC0Xr/2ILdAy7IcJVaD6B3dWD6mAsHAs9D+xI2qETaTmZn7UCpcUjHnfoXofo6R6M185TiWXkPGZCG2p5vThLo6q7O+LGvI81Ie84umy2aVxkEpkx+5Xo4D1Hcv9IQ+jlpZ1npMwIDAQABoyEwHzAdBgNVHQ4EFgQUH6rYQ7bLBi9dpF7/AeGbQnaGE0kwDQYJKoZIhvcNAQELBQADggEBAG0oJ+kgEBqOBGJhY79YI6rcBX0SbNyOwPoolAaijkSJkX+CUP1JOokHZ5pCeXmAYnFxfMnVktZRSoOB6An1MVRt8PUO8WoU//Ftu3+3ljZ4BV+tpBVBkUTHjjRS2NUrvSY2r1fIPiDn/ZQUQEnB2k/gok/h0HpVEA4WU6/f40VbbD21EQL5FXsPJFS6TVstTdC8A65jF3QKq0u68wrQNgHhtGiaprYRP3+NapvW0hT98nEVUlCVM85Y+4PsKBCCbt1XKnoHmQ0aFlsJXXtIRlKRqnT0uc0dgurnz4L+5Z/laS7nr8Z+CmqY2TtdP+28GEP0NvcKYv3kuTFVUbkFW2w+X8ix6fZXYOpaDPeD1e/gN0Vmeg==
  truststore.jks: /u3+7QAAAAIAAAACAAAAAgAQbWVzc2FnaW5nLXRlc3RlcgAAAXfwO794AAVYLjUwOQAAAtswggLXMIIBv6ADAgECAgQsGqEMMA0GCSqGSIb3DQEBCwUAMBsxGTAXBgNVBAMTEG1lc3NhZ2luZy10ZXN0ZXIwIBcNMjEwMjIzMTIwMjMxWhgPMzAyMDA2MjYxMjAyMzFaMBsxGTAXBgNVBAMTEG1lc3NhZ2luZy10ZXN0ZXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC/+YiyjddMKznXhtQnJyce/5jVRjlc6IEOUro5WZ8+sM8fvrcEqZ+NpQgfRcyQBpHiEvlW219ZgQKOjk6LlwSwU1lMONQJif5pkiXW6g8mugsKWMtQNO1CcjgZi1JQwnSt+IprlgCzFC8UoVtjxTTgLBVh8WXIQQAJ+BJsH+ml9EMdpbs4xtZ9hOR7I8SzVvqMV+oB29rS9lOc/A3PffOEkmHsggzZZq+P62UoPF2rgiSlKEtI2tovt48oEwfTCFRsFJoWwoWPLcnX1ksQ1f7/Owe/5rsXVpMAFXMIvjKY7LVbXaMwG4s0z05REPJQQs86H8qNZfgOOvW7bBcaFNEpAgMBAAGjITAfMB0GA1UdDgQWBBQmYQfJdmWcCdEcGpoxp/WawWpc2DANBgkqhkiG9w0BAQsFAAOCAQEAIBr59i7uoTcxUm5k6TT+gvfyp0qbZ/Hqw98mZqF6Uftz18bwARPfVizK2YrEI57cqJIaxakqkS5D72M1+SynRia9Id7vr0LCq4C2OIGf4I+sYUZJGLt5ZIFgysxqE/DsZVqr928HyyfvKI4xOP5zGZEGn4kPT+LYC/eDtjxprnDGJOI0Q9K2MQl8gjRu6jdUaXP0BjfWOjE4oXZNPh7s205khLkn/nHXqEGLbLxnUcKMQgYuLD3FHaSNtPcpKOViFadRLaik+TCHFpmp6bWGQyFBqTMrJvS/Fz1Zi1SnCtJphA39qVm7CJQ5nDH4ONSab3Ft+hDbpf7YaI8S+BQXgAAAAAIACmFtcS1icm9rZXIAAAF38Du/dwAFWC41MDkAAALPMIICyzCCAbOgAwIBAgIEXlbPoTANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwphbXEtYnJva2VyMCAXDTIxMDIwNDIzMTg1N1oYDzMwMjAwNjA3MjMxODU3WjAVMRMwEQYDVQQDEwphbXEtYnJva2VyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuJtbgCKALKlDUgufCGqqO8woUrFefOw+r+pfIt+xloilWnqf8L0Vri/xU0PEI2UZuZIq6kIHBtISUi+RkGFLtUwkcpo1Y16V4dASsFYaGxdbxfNHuDRQ7vTJdKh8argGviFYaRjTaGRhX3ga9Ne7/5u9dzTaXI19GgamYsEyFB0a2kN7Qf6PC+oRy9adgOalY5Lr375q+PEDYAGL32NOHDQgHzc8jLmaIqdjEFfl1O0vmFrQtgUyKUZJenLNylQf8WZQM3gB1KJVIgzh7ClVCyTkWHGpKMriEV0P/AEwQA3xLqy0G/bo7rQE+4q6oUFTKhzXfkzU0TgoW13NQUn8EwIDAQABoyEwHzAdBgNVHQ4EFgQUrIm0L3RfbnKj8mG40kU4YIqCITMwDQYJKoZIhvcNAQELBQADggEBAE0XsF8XKjXj24N1xjBPLzVNEKiPfOFVZQlAUZjniB5atxBX3oTdUb2qUjnta0kcioEYJt6tKWYmRU9t1acJ+MDIPxv6zPYAstXak9Ut18QPyyKzVz3lwP/xYMN+Xw0xUgWrsC6j+3CfnH9d6MLbTTgw3w23ufgCa9Z5lzwzGBD76TKWmzmbFk/TsqiGX4zU/AS4hbrLXQYV8YwrW/5YsCc0vASUeEiB5erfjpjUgxFJiAdM2vEPIqhGaHDdcI8bEjWH5GShl768PqSipmb8w0WVo67M/wuxvf/ukbrpq0aHa5SDf9PkiBwJPem0Ne5SwBxOZCLz3VtEvkNwd5s4eJHRoPcpd5nFVcb+GEaw/uLOTh4QeA==