apiVersion: interconnectedcloud.github.io/v1alpha1
kind: Interconnect
metadata:
  name: interconnect-cluster-mirror
spec:
  addresses:  
  - prefix: app.queue
    distribution: balanced
    waypoint: true
  - prefix: app.queue-mirror
    distribution: balanced
    waypoint: true
  deploymentPlan:
    role: interior
    placement: Any
    size: 1
  listeners:  
    - port: 5672
    - authenticatePeer: false
      expose: true
      http: true
      port: 8080
    - port: 5671
      sslProfile: default
      expose: true
  interRouterListeners:
    - port: 55671
      sslProfile: default
      expose: true
  connectors:
    - name: amq-broker-mirror
      host: amq-broker-mirror-hdls-svc.amq-messaging-mirror.svc.cluster.local
      port: 5672
      routeContainer: true
  autoLinks:
    - address: 'app.queue-mirror'
      direction: in
      connection: amq-broker-mirror
    - address: 'app.queue-mirror'
      direction: out
      connection: amq-broker-mirror
  interRouterConnectors:
    - host: interconnect-cluster-55671-amq-messaging.apps.cluster-4cc6.4cc6.example.opentlc.com
      port: 443
      verifyHostname: false
      sslProfile: default
      name: interconnect-cluster
  sslProfiles:
  - name: default
    credentials: interconnect-cluster-mirror-default-credentials
    caCert: interconnect-cluster-mirror-default-credentials