apiVersion: interconnectedcloud.github.io/v1alpha1
kind: Interconnect
metadata:
  name: interconnect-cluster-b
spec:
  addresses:  
  - prefix: app.queue
    distribution: balanced
    waypoint: true
  - prefix: app.addr
    distribution: multicast
  deploymentPlan:
    role: interior
    placement: Any
    size: 1
  listeners:  
    - port: 5672
    - authenticatePeer: false
      expose: true
      http: true
      port: 8080
    - port: 5671
      sslProfile: default
      expose: true
  interRouterListeners:
    - port: 55671
      sslProfile: default
      expose: true
  connectors:
    - name: amq-broker-b-0
      host: amq-broker-b-0-svc
      port: 5672
      routeContainer: true
    - name: amq-broker-b-1
      host: amq-broker-b-1-svc
      port: 5672
      routeContainer: true
  linkRoutes:
    - prefix: $coordinator
      direction: in
      connection: amq-broker-b-0
    - prefix: 'app.queue.b'
      direction: in
      connection: amq-broker-b-0
    - prefix: 'app.queue.b'
      direction: out
      connection: amq-broker-b-0
    - prefix: $coordinator
      direction: in
      connection: amq-broker-b-1
    - prefix: 'app.queue.b'
      direction: in
      connection: amq-broker-b-1
    - prefix: 'app.queue.b'
      direction: out
      connection: amq-broker-b-1
  autoLinks:
    # - address: 'app.queue.b'
    #   direction: in
    #   connection: amq-broker-b
    # - address: 'app.queue.b'
    #   direction: out
    #   connection: amq-broker-b
    - address: 'app.queue.perf'
      direction: in
      connection: amq-broker-b
    - address: 'app.queue.perf'
      direction: out
      connection: amq-broker-b
  interRouterConnectors:
    #https://interconnect-cluster-central-55671-amq-messaging-central.apps.cluster-33cc.33cc.example.opentlc.com/
    - host: interconnect-cluster-central
      port: 55671
      verifyHostname: false
      sslProfile: default
      name: interconnect-cluster
  sslProfiles:
  - name: default
    credentials: interconnect-cluster-b-default-credentials
    caCert: interconnect-cluster-b-default-credentials