apiVersion: interconnectedcloud.github.io/v1alpha1
kind: Interconnect
metadata:
  name: interconnect-cluster-b
spec:
  addresses:  
  - prefix: app
    distribution: balanced
    waypoint: true
  deploymentPlan:
    role: interior
    placement: Any
    size: 1
  listeners:  
    - port: 5672
    - authenticatePeer: false
      expose: true
      http: true
      port: 8080
    - port: 5671
      sslProfile: default
      expose: true
  interRouterListeners:
    - port: 55671
      sslProfile: default
      expose: true
  connectors:
    - name: amq-broker-b
      host: amq-broker-b-amq-headless.amq-messaging-b.svc.cluster.local
      port: 5672
      routeContainer: true
  linkRoutes:
    - prefix: 'app.queue-b'
      direction: in
      connection: amq-broker-b
    - prefix: 'app.queue-b'
      direction: out
      connection: amq-broker-b
  # autoLinks:
  #   - address: 'app.queue-b'
  #     direction: in
  #     connection: amq-broker-b
  #   - address: 'app.queue-b'
  #     direction: out
  #     connection: amq-broker-b
  interRouterConnectors:
    #https://interconnect-cluster-central-55671-amq-messaging-central.apps.cluster-33cc.33cc.example.opentlc.com/
    - host: interconnect-cluster-central-55671-amq-messaging-central.apps.cluster-33cc.33cc.example.opentlc.com
      port: 443
      verifyHostname: false
      sslProfile: default
      name: interconnect-cluster
  sslProfiles:
  - name: default
    credentials: interconnect-cluster-b-default-credentials
    caCert: interconnect-cluster-b-default-credentials