apiVersion: interconnectedcloud.github.io/v1alpha1
kind: Interconnect
metadata:
  name: interconnect-cluster-a
spec:
  addresses:  
  - prefix: app.queue-a
    distribution: balanced
    waypoint: true
  deploymentPlan:
    role: interior
    placement: Any
    size: 1
  listeners:  
    - port: 5672
    - authenticatePeer: false
      expose: true
      http: true
      port: 8080
    - port: 5671
      sslProfile: default
      expose: true
  interRouterListeners:
    - port: 55671
      sslProfile: default
      expose: true
  connectors:
    - name: amq-broker-a
      host: amq-broker-a-hdls-svc.amq-messaging-a.svc.cluster.local
      port: 5672
      routeContainer: true
  linkRoutes:
    - prefix: 'app.queue-a.a'
      direction: in
      connection: amq-broker-a
    - prefix: 'app.queue-a'
      direction: out
      connection: amq-broker-a

  # autoLinks:
  #   - address: 'app.queue-a'
  #     direction: in
  #     connection: amq-broker-a
  #   - address: 'app.queue-a'
  #     direction: out
  #     connection: amq-broker-a
  sslProfiles:
  - name: default
    credentials: interconnect-cluster-a-default-credentials
    caCert: interconnect-cluster-a-default-credentials
