apiVersion: interconnectedcloud.github.io/v1alpha1
kind: Interconnect
metadata:
  name: interconnect-cluster-b
spec:
  addresses:  
  - prefix: app.queue-b
    distribution: balanced
    waypoint: true
  deploymentPlan:
    role: interior
    placement: Any
    size: 1
  listeners:  
    - port: 5672
    - authenticatePeer: false
      expose: true
      http: true
      port: 8080
    - port: 5671
      sslProfile: default
      expose: true
  interRouterListeners:
    - port: 55671
      sslProfile: default
      expose: true
  connectors:
    - name: amq-broker-b
      host: amq-broker-b-hdls-svc.amq-messaging-b.svc.cluster.local
      port: 5672
      routeContainer: true
  autoLinks:
    - address: 'app.queue-b'
      direction: in
      connection: amq-broker-b
    - address: 'app.queue-b'
      direction: out
      connection: amq-broker-b
  interRouterConnectors:
    - host: interconnect-cluster-a-55671-amq-messaging-a.apps.cluster-f646.f646.example.opentlc.com
      port: 443
      verifyHostname: false
      sslProfile: default
      name: interconnect-cluster
  sslProfiles:
  - name: default
    credentials: interconnect-cluster-b-default-credentials
    caCert: interconnect-cluster-b-default-credentials