---
docker:
  registries:
    - registry.hpel.lan
  dns: 
    - 192.168.8.254
    - 8.8.8.8

appimages:
  - name: beeref
    url: https://github.com/rbreu/beeref/releases/download/v0.2.0/BeeRef-0.2.0-linux
    icon: https://raw.githubusercontent.com/rbreu/beeref/main/beeref/assets/logo.png
  - name: freac
    url: https://github.com/enzo1982/freac/releases/download/v1.1.5/freac-1.1.5-linux-x86_64.AppImage
    icon: https://github.com/alainpham/appp/raw/master/freac/icon.png
  - name: mlvapp
    url: https://github.com/ilia3101/MLV-App/releases/download/QTv1.13/MLV.App.v1.13.Linux.x86_64.AppImage
    icon: https://github.com/alainpham/appp/raw/master/mlvapp/icon.png
  - name: plex-media-player
    url: https://knapsu.eu/data/plex/Plex_Media_Player_2.58.1-ae73e074_x64.AppImage
    icon: https://github.com/alainpham/appp/raw/master/plex-media-player/icon.png
  - name: rawtherapee
    url: https://rawtherapee.com/shared/builds/linux/RawTherapee_5.8.AppImage
    icon: https://github.com/alainpham/appp/raw/master/rawtherapee/icon.png
  - name: viber
    url: https://download.cdn.viber.com/desktop/Linux/viber.AppImage
    icon: https://github.com/alainpham/appp/raw/master/viber/icon.png