---
docker:
  registries:
    - registry.hpel.lan
  dns: 
    - 192.168.8.254
    - 8.8.8.8

appimages:
  - name: beeref
    url: http://fileserver.hpel.lan/camel/download?file=BeeRef-0.2.0-linux 
    hash: sha256:8e98dfd3b9783649805e067238b3f4df00c1da24b012b952e44757510cf241d2
    icon: https://raw.githubusercontent.com/rbreu/beeref/main/beeref/assets/logo.png
  - name: freac
    url: http://fileserver.hpel.lan/camel/download?file=freac-1.1.5-linux-x86_64.AppImage
    hash: sha256:db314a1eb46cf7e863587934e520a9499349ad0f4b6a2ac32f313b3797482c84
    icon: https://github.com/alainpham/appp/raw/master/freac/icon.png
  - name: mlvapp
    url: http://fileserver.hpel.lan/camel/download?file=MLV.App.v1.13.Linux.x86_64.AppImage
    hash: sha256:e765010c3b73254fad3ab907e88dbed07175f38deca7ab1d7a0484624dfcee09
    icon: https://github.com/alainpham/appp/raw/master/mlvapp/icon.png
  - name: plex-media-player
    url: http://fileserver.hpel.lan/camel/download?file=Plex_Media_Player_2.58.1-ae73e074_x64.AppImage
    hash: sha256:1cfcaac5eedf8d46fe5a35a13921f55c44862736cee043c03a31053e2d308eb4
    icon: https://github.com/alainpham/appp/raw/master/plex-media-player/icon.png
  - name: rawtherapee
    url: http://fileserver.hpel.lan/camel/download?file=RawTherapee_5.8.AppImage
    hash: sha256:c212b15f39d02bd8f8a54358045116cbac757ea155e5378e09d727a513895928
    icon: https://github.com/alainpham/appp/raw/master/rawtherapee/icon.png
  - name: viber
    url: http://fileserver.hpel.lan/camel/download?file=viber.AppImage
    hash: sha256:280ab109ec68b579cff6fd4db108c5d2af9fb60405cc0e566eaf54d24530e888
    icon: https://github.com/alainpham/appp/raw/master/viber/icon.png

rawpackages:
  - name: mvn
    url: http://fileserver.hpel.lan/camel/download?file=apache-maven-3.8.4-bin.tar.gz
    hash: sha256:2cdc9c519427bb20fdc25bef5a9063b790e4abd930e7b14b4e9f4863d6f9f13c
    executable: apache-maven-3.8.4/bin/mvn
    recreate: false
  - name: code
    url: http://fileserver.hpel.lan/camel/download?file=vscode-1.62.3.tar.gz
    hash: sha256:490eab158f6522cef0859138761caa35ea39ad90d3902567403691a77e5dc871
    executable: VSCode-linux-x64/bin/code
    recreate: true

appimagesweb:
  - name: beeref
    url: https://github.com/rbreu/beeref/releases/download/v0.2.0/BeeRef-0.2.0-linux
    hash: sha256:8e98dfd3b9783649805e067238b3f4df00c1da24b012b952e44757510cf241d2
    icon: https://raw.githubusercontent.com/rbreu/beeref/main/beeref/assets/logo.png
  - name: freac
    url: https://github.com/enzo1982/freac/releases/download/v1.1.5/freac-1.1.5-linux-x86_64.AppImage
    hash: sha256:db314a1eb46cf7e863587934e520a9499349ad0f4b6a2ac32f313b3797482c84
    icon: https://github.com/alainpham/appp/raw/master/freac/icon.png
  - name: mlvapp
    url: https://github.com/ilia3101/MLV-App/releases/download/QTv1.13/MLV.App.v1.13.Linux.x86_64.AppImage
    hash: sha256:e765010c3b73254fad3ab907e88dbed07175f38deca7ab1d7a0484624dfcee09
    icon: https://github.com/alainpham/appp/raw/master/mlvapp/icon.png
  - name: plex-media-player
    url: https://knapsu.eu/data/plex/Plex_Media_Player_2.58.1-ae73e074_x64.AppImage
    hash: sha256:1cfcaac5eedf8d46fe5a35a13921f55c44862736cee043c03a31053e2d308eb4
    icon: https://github.com/alainpham/appp/raw/master/plex-media-player/icon.png
  - name: rawtherapee
    url: https://rawtherapee.com/shared/builds/linux/RawTherapee_5.8.AppImage
    hash: sha256:c212b15f39d02bd8f8a54358045116cbac757ea155e5378e09d727a513895928
    icon: https://github.com/alainpham/appp/raw/master/rawtherapee/icon.png
  - name: viber
    url: https://download.cdn.viber.com/desktop/Linux/viber.AppImage
    hash: sha256:280ab109ec68b579cff6fd4db108c5d2af9fb60405cc0e566eaf54d24530e888
    icon: https://github.com/alainpham/appp/raw/master/viber/icon.png

rawpackagesweb:
  - name: maven
    url: https://dlcdn.apache.org/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz
    hash: sha256:2cdc9c519427bb20fdc25bef5a9063b790e4abd930e7b14b4e9f4863d6f9f13c
    executable: 



kdeconf:
  sddmtheme:
    name: plasma-chili

jack:
  - name: noise-repellent_0.1.5-1kxstudio2_amd64.deb
    url: http://ppa.launchpad.net/kxstudio-debian/plugins/ubuntu/pool/main/n/noise-repellent/noise-repellent_0.1.5-1kxstudio2_amd64.deb


ips:
  rentman: 172.18.0.20 
  bqueue: 172.18.0.21
  plex: 172.18.0.22
  teddycast: 172.18.0.23
  

  nexus: 172.18.0.41
  registry: 172.18.0.42
  regui: 172.18.0.45
  traefik: 172.18.0.43
  fileserver: 172.18.0.47

  zookeeper: 172.18.0.61
  kafka: 172.18.0.62
  kafdrop: 172.18.0.63
  kafkaexporter: 172.18.0.64

  prometheus: 172.18.0.70
  grafana: 172.18.0.71
  loki: 172.18.0.72

  amqbroker: 172.18.0.115
  

# states can absent present stopped started
appstate: started
recreate: false
