# my global config
global:
  scrape_interval: 12s 
  evaluation_interval: 12s 
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'node'
    static_configs:
      - targets: 
          - "asus:9100"
          - "ampi:9100"
          - "hpel:9100"
          - "work:9100"
          - "hppa:9100"
          - "leol:9100"

  - job_name: 'amqbroker'
    static_configs:
      - targets: 
          - "amqbrokercons.hpel.lan:80"
        labels:
          namespace: "amq"
          kubernetes_pod_name: "amq-broker-hpel"
          broker: "amq-broker-hpel"
          kubernetes_namespace: "amq"
          statefulset_kubernetes_io_pod_name: "amq-broker-hpel"
          node_name: "hpel"


  - job_name: 'camelquarkus'
    static_configs:
      - targets: 
          - "bqueue.work.lan"
        labels:
          namespace: "camel"
          kubernetes_pod_name: "bqueue-work"
          node_name: "work"
      - targets: 
          - "bqueue.hpel.lan"
        labels:
          namespace: "camel"
          kubernetes_pod_name: "bqueue-hpel"
          node_name: "hpel"
      - targets: 
          - "bqueue.hppa.lan"
        labels:
          namespace: "camel"
          kubernetes_pod_name: "bqueue-hppa"
          node_name: "hppa"
      - targets: 
          - "bqueue.leol.lan"
        labels:
          namespace: "camel"
          kubernetes_pod_name: "bqueue-leol"
          node_name: "leol"