kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: amq-broker-operator
subjects:
- kind: ServiceAccount
  name: amq-broker-operator
  # you will have to deploy the operator into this namespace, whatever it is
  namespace: default
roleRef:
  kind: ClusterRole
  name: amq-broker-operator
  apiGroup: rbac.authorization.k8s.io
