apiVersion: apps/v1
kind: Deployment
metadata:
  name: amq-broker-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: amq-broker-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: amq-broker-operator
        com.company: Red_Hat
        rht.prod_name: Red_Hat_Integration
        rht.prod_ver: 2021.Q4
        rht.comp: Broker_AMQ
        rht.comp_ver: 7.9.1
        rht.subcomp: broker-amq-operator
        rht.subcomp_t: application
    spec:
      containers:
      - args:
        # Explicitly set the logging level.
        # Valid values are debug, info, and error
        # from most to least.
        # If running entrypoint_debug then use '-- --zap-level debug'
        - '--zap-level info'
        - '--zap-encoder console'
        command:
        - /home/amq-broker-operator/bin/entrypoint
        env:
        - name: OPERATOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['name']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
          # to watch all namespaces use '*' or empty ''
          # to watch multiple namespaces use comma separated list 'ns1,ns2'
          # default is to watch the operator's namespace (backward compatibility)
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # By default the *_782 values are utilized.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # X86_64 / AMD64 / default
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_781
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:0.3-3
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:f58678f03a250dbb296ebeb112c9150340155799ba4dad9e90bf347b9ed0ca7b
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_782
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:0.3-7
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:d2aaf3c7ec96e405467833f4908060f06bc5dff1f34cbc4df49885492f7ad11b
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_783
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:0.3-9
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:0b2126cfb6054fdf428c1f43b69e36e93a09a49ce15350e9273c98cc08c6598b
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_790
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:0.4-8.1634738912
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:e03945756d86bd189e8c33027fa668d2065c168510085dfd06defd9f40d3e0ab
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_791
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:0.4-10
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:813f911d5c554fd3a9abe458ffe9d22466fd2a7c385d8f201ef1c02a36634ea7
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_781
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.8-3
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:0d857b95084e39c011651be89482d4dcc77c2d1c3ac3c6a819f3c9d5a57a425f
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_782
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.8-8
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:dae59c0aa98a1c1d0a5ab10d59db102a2c1ab089c9863e04a2429f40a672c41c
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_783
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.8-11
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:c5f4c08e068b9721967cf7c7cbd9a9e93fb5e39b264dd13b653e99d8f3fa9e0e
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_790
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.9-10.1634738327
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:5d39f26f06769fe5c989ea0e0ee8f9166120e152ce2c9bc3336fc8d7cab2ff92
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_791
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.9-12
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:b4a7a1b43d1b9517f3c567fbcd7a61d7e63c5b2b950d0fb9b521942347e47368

        # PPC64LE
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_781_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8:0.3-3
          value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8@sha256:5ff28e3062d3eabb9f52d8271b837fdab06cafbd8b8f732b1bc00de49ad69aad
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_782_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8:0.3-4
          value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8@sha256:326d8722c23aa8851cdad3fdc2d9c4823cd3f63d1e4668cf3a9a4c273a0b84e1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_783_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8:0.3-5
          value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8@sha256:56282c6a461e945a83bffb13d3f3d8d9621800f0fc9cd755a75d21eacd8f5fbf
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_790_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8:0.4-4
          value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8@sha256:c3ac4602b48867f3d4f7cc0efd5c9f133098e409626cfb402f80386ff460dbf4
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_791_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8:0.4-7
          value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8@sha256:1a9f13fd565113055b2aa2022bd0709a63c1dc058a8570e0fd7eba5c7b101334
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_781_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8:7.8-8
          value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8@sha256:f2651cb097eb631fc6af90e4a8404d36516aa2205c546125bf0c37739ab525fa
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_782_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8:7.8-14
          value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8@sha256:ba0f5df7da08bc030ff5e0e68ecb52a931c25f6b67c6556aa8a9661c82d69d42
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_783_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8:7.8-15
          value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8@sha256:34ab1f66d8daa544e3823464383e9788e307665c875499838fbed95f3a74a4dd
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_790_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8:7.9-9
          value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8@sha256:97c3aa5673610875a53571449f7d5210ae8d675072d044f17b416725ed0dba88
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_791_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8:7.9-12
          value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8@sha256:d4010af53429502f41d722c39d69a7bb147bb06d19e3d4a69de70dbe88e3990e

        # S390X
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_781_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8:0.3-3
          value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8@sha256:5ff28e3062d3eabb9f52d8271b837fdab06cafbd8b8f732b1bc00de49ad69aad
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_782_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8:0.3-4
          value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8@sha256:326d8722c23aa8851cdad3fdc2d9c4823cd3f63d1e4668cf3a9a4c273a0b84e1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_783_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8:0.3-5
          value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8@sha256:56282c6a461e945a83bffb13d3f3d8d9621800f0fc9cd755a75d21eacd8f5fbf
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_790_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8:0.4-4
          value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8@sha256:c3ac4602b48867f3d4f7cc0efd5c9f133098e409626cfb402f80386ff460dbf4
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_791_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8:0.4-7
          value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8@sha256:1a9f13fd565113055b2aa2022bd0709a63c1dc058a8570e0fd7eba5c7b101334
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_781_s390x
          #value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8:7.8-8
          value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8@sha256:f2651cb097eb631fc6af90e4a8404d36516aa2205c546125bf0c37739ab525fa
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_782_s390x
          #value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8:7.8-14
          value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8@sha256:ba0f5df7da08bc030ff5e0e68ecb52a931c25f6b67c6556aa8a9661c82d69d42
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_783_s390x
          #value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8:7.8-15
          value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8@sha256:34ab1f66d8daa544e3823464383e9788e307665c875499838fbed95f3a74a4dd
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_790_s390x
          #value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8:7.9-9
          value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8@sha256:97c3aa5673610875a53571449f7d5210ae8d675072d044f17b416725ed0dba88
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_791_s390x
          #value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8:7.9-12
          value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8@sha256:d4010af53429502f41d722c39d69a7bb147bb06d19e3d4a69de70dbe88e3990e

        #image: registry.redhat.io/amq7/amq-broker-rhel8-operator:7.9-7
        image: registry.redhat.io/amq7/amq-broker-rhel8-operator@sha256:e36606b2eb8da63f9b5f8bfef771e21e5abc60fcca6038b531bc65c132d27d10

        # If floating tags are configured above you may want to set this to true.
        #imagePullPolicy: Always

        name: amq-broker-operator
        resources: {}
      serviceAccountName: amq-broker-operator
