---
apiVersion: "apps.openshift.io/v1"
kind: "DeploymentConfig"
metadata:
  annotations:
    fabric8.io/git-commit: "decc7b64aefddac1a84d1d2becb73ccac4ec5890"
    fabric8.io/git-branch: "master"
    fabric8.io/git-url: "git@github.com:alainpham/dev-env-scripts.git"
  labels:
    app: "messaging-tester"
    group: "demo"
  name: "messaging-tester"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    app: "messaging-tester"
    group: "demo"
  strategy:
    rollingParams:
      timeoutSeconds: 3600
    type: "Rolling"
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: "decc7b64aefddac1a84d1d2becb73ccac4ec5890"
        fabric8.io/git-branch: "master"
        fabric8.io/git-url: "git@github.com:alainpham/dev-env-scripts.git"
      labels:
        app: "messaging-tester"
        group: "demo"
    spec:
      containers:
      - env:
        - name: "AB_JMX_EXPORTER_CONFIG"
          value: "prometheus-config.yml"
        image: "alainpham/messaging-tester:latest"
        imagePullPolicy: "Always"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: "/actuator/health"
            port: 8081
            scheme: "HTTP"
          initialDelaySeconds: 180
          successThreshold: 1
        name: "spring-boot"
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
        - containerPort: 9779
          name: "prometheus"
          protocol: "TCP"
        - containerPort: 8778
          name: "jolokia"
          protocol: "TCP"
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: "/actuator/health"
            port: 8081
            scheme: "HTTP"
          initialDelaySeconds: 10
          successThreshold: 1
        resources:
          limits:
            cpu: "2.0"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "128Mi"
        securityContext:
          privileged: false
        volumeMounts:
        - mountPath: "/deployments/tls"
          name: "tls-secret-volume"
          readOnly: true
        - mountPath: "/deployments/config"
          name: "prop-secret-volume"
          readOnly: true
      volumes:
      - name: "tls-secret-volume"
        secret:
          defaultMode: 420
          secretName: "messaging-tester-tls-secret"
      - name: "prop-secret-volume"
        secret:
          defaultMode: 420
          secretName: "messaging-tester-prop-secret"
  triggers:
  - type: "ConfigChange"
---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/git-commit: "decc7b64aefddac1a84d1d2becb73ccac4ec5890"
    fabric8.io/git-branch: "master"
    fabric8.io/git-url: "git@github.com:alainpham/dev-env-scripts.git"
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
  labels:
    expose: "true"
    app: "messaging-tester"
    group: "demo"
  name: "messaging-tester"
spec:
  ports:
  - name: "http"
    port: 8080
    protocol: "TCP"
    targetPort: 8080
  selector:
    app: "messaging-tester"
    group: "demo"
---
apiVersion: "v1"
kind: "Route"
metadata:
  annotations:
    haproxy.router.openshift.io/balance: "roundrobin"
  labels:
    app: "messaging-tester"
    group: "demo"
  name: "messaging-tester"
spec:
  port:
    targetPort: "http"
  to:
    kind: "Service"
    name: "messaging-tester"
status: {}

---
kind: Secret
apiVersion: v1
metadata:
  name: "messaging-tester-prop-secret"
type: Opaque
stringData: 
  application.properties: |
    logging.config=classpath:logback-dev.xml

    # the options from org.apache.camel.spring.boot.CamelConfigurationProperties can be configured here
    camel.springboot.name=messaging-tester

    # lets listen on all ports to ensure we can be invoked from the pod IP
    server.address=0.0.0.0
    management.server.address=0.0.0.0
    # lets use a different management port in case you need to listen to HTTP requests on 8080
    server.port=8080
    management.server.port=8081

    # disable all management enpoints except health
    endpoints.enabled = false
    endpoints.health.enabled = true

    cxf.path=/services

    camel.component.servlet.mapping.contextPath=/camel/*
    camelrest.contextPath=/camel
    camelrest.apiversion=1.0-SNAPSHOT


    jms.uri=amqp://interconnect-cluster:5672
    jms.user=user
    jms.pwd=password
    jms.sslEnabled=true
    jms.trustStorePath=tls/truststore.p12
    jms.trustStorePassword=password
    jms.keyStorePath=tls/keystore.p12
    jms.keyStorePassword=password
    jms.cache.level=CACHE_CONSUMER
    jms.concurrentConsumers=10
    jms.java.naming.factory.initial=org.apache.qpid.jms.jndi.JmsInitialContextFactory
    jms.connectionFactory.default=${jms.uri}?transport.trustAll=true
    
    topic.loadtrigger=app.addr
    queue.defaultapp=app.queue
    queue.perf=app.perf

---
kind: Secret
apiVersion: v1
metadata:
  name: "messaging-tester-tls-secret"
type: Opaque
data:
  keystore.p12: MIIJcQIBAzCCCSoGCSqGSIb3DQEHAaCCCRsEggkXMIIJEzCCBW8GCSqGSIb3DQEHAaCCBWAEggVcMIIFWDCCBVQGCyqGSIb3DQEMCgECoIIE+zCCBPcwKQYKKoZIhvcNAQwBAzAbBBT5EO7LJMYs76hvLFhWsoEiJMqWvgIDAMNQBIIEyCCWUL4ENnRkU7jivGnb/0pVGt04EH/tV0hmvjZgr23hNIVvNozplyZyJal0INgqXjvh02erOqDgkKEmARCuAZW3MtzuGJa+fFIPZY6fdOromDT7IDTkjAl9g8VPDXcpmqvq0bKXDzIM6e+ce03+3L3emNHiws3PFXYcEmVO21cjh18vKRChcuUwaxdqYrbPvCVRxudNI0jS/bQTExNLY9nM3zhP/Rr3EmInKK09bXiIvPMZ585O0wsM+EPRATpNrcU365PijBQw+M6p8C2J3TdpOTOFZwkICbvEN8UgHyttOwmdhQzQOsYJcabjzfpdQbVSaTgMowLYlhzLg8BlzgSJ1a5MsPtCLt2Nz9LATnSK7jzOw6tY27TrVBFjK2lxldKia3Bm+ZdXMSSC3KQa01qFkrrEmtcou0yrGrlaUgFG+PbMf9FP8WehZAQtEYmjuMMLpZ9QPXm3syq3dL6JMoeYnvx4pxmmVO3s5T5a3wi8LqHTMUI0T6nJXxjP6mUWjb8oHaaJlUUbqUJiVkX0iLq03ggE+GTROSQkamcJDcyd8QeFVL8Jzm9YG3TYbYhso/ilkcswu7EblVXtvp7l8RwqyK15l2dvX4NbmzknhfTGxA4XL92ZGa1SGfzne5NOxZunTY3EBTb0oTMRc/oWkhYVFT2Ou5tAExioeubOV6q6F0l2I8S/WjZ8zPflECHC2tCIyxO2T1b9sSPOfP9Ei3qwRdDWyKsBiXGzKgJQ9qZOzIuIRQ5w6G8w2oVz0bkLlHQyT5Hbm3cxNXnHidE9UYG9cVXz3cspmyfkiOVb1ojbuYBu9SqgNYPWrw6y339VQ1VrNSDiIVeVidKFwI0vIpHrIDUZXMFPNABxsr9IctfsTQW7LEqYmCx+BXb2fprWX1D/OXz0H5xogZpPC9WRAdYF5zC9eA3K83YhQjeWGimIwpAOgaGOaj5xmgG6Py0wdp1K5qu946wj4/b9Jk9VNMLuSLO4CNDWnzbPtlGxAZP6cONcjmrvPqgvAcOsDvyQJEqPH7gS+ENSqD2ivz1RTIcBKo0TZIRp6wN+YbjK2f07+f4IZ8RnFOz3EIhWSUcoeeqMXgxbMpt9XsIiXMJW3zKAozrgNLnN48iW8Ooi2krISFFQ2iEcOxjOGX+RtzSkG0srPWxI7kZtMb8FIlhA2+9wW58tSjj96Gp+g8SPa41Wc63pY6rUePbQuzCMr3luu8Vz4u3T52mIQnalrSBFZkGZgrTQhOTMMYjxESrFiP4i9nBygwedB/AVYt9AMVwZPcl7zvVZHUQud3G7zLzn7/MXM/qS61+o2dJzA++WCZURseoZcpaIIgPpSSUciJogaKIzIby0sWAbW12DWi1beis+zD1ksiA4CUj4dGh/o6dEx3A7Fk8Xl7WWzhVmdPPZKIsPlKlau/c1I1Gtx+7bMBrV8qmzXC76F+Gs5uJwUvFR5OyRxK7b2A1rNPcO0WbIU237MLb0Uz4ajplYKrl+lWv+51OTyq4vgbK42UgQVvofQAM/SEGaMCgRE4ajdPv5YX3yuAVsQIsmFQSSMCrOOpqvBlWIC4gcLnz0+msR6puegS3ZrVjg2SYtjCTvzaDj/pWu9O6s2vvyA6XMvl+IgEWQxSDOHwMV8jFGMCEGCSqGSIb3DQEJFDEUHhIAYQBtAHEAYwBsAGkAZQBuAHQwIQYJKoZIhvcNAQkVMRQEElRpbWUgMTYxMTQxNjQyODE0MjCCA5wGCSqGSIb3DQEHBqCCA40wggOJAgEAMIIDggYJKoZIhvcNAQcBMCkGCiqGSIb3DQEMAQYwGwQUSfZaPQe9GtCa6eMyIb/eSFcI4mUCAwDDUICCA0hKpmgMG1SjxP/Fbx3af+tyug8SGKRftOUipPFWc5ju2RT803wHsdsQUKirl7JHsjH2HL7Gr85Ar2/oU0zhrWH42l3uEXXhjwf8BCuuOnuKJy6WjIvStqci1FUyDS2o9LBJbNbetyoUxGwfD/wFYPVSXBG2+asChLRev5q5wFC5FY2QAVhW/7sMokscdOrpIi/eN3If1/LBQvCGbx4l+IIiwF9Zer2WtpRGpRWwhZCBg+MFCkJliJNMoc/SL3u4s0WqC3AFdHet8PaS3NjEz/7MU5CF1zk3fTEwSXnMFUaXgUIsCgCXnxI/JFximjGBz+kE0UQKIdN8w+HUlUUC40zzenbwkAe3M5tNKHVIiWWw3zb9/XJJtq05R6NdNIRdAZxPyFwDUHYO4Nu8bmqNHSBvd1nUm/YUCxNrUjGwPGP/geqLwPbkIDHLXDwgRu1W6sPwTVlLYruJCQYkQWz3RLGCFk2VkC6W6bI6vATpFbuPjYyNxiiYRZnEeLQhhV9ouh8tdDXZtDNuygQxNa6oFUwFIzT8Aoc5WtaL2wDv8Kfxw/Azm/6iNK1W5symYuKi1Qhgllwr7mJFBrhVROIvz6Xp8T5T1rqjKML9q3Ot8cRFxAQqo9uYU08090ftn6q1k/8dVn0eARqqQqL3ix/Pd185N44xlqaaEJ1mi2qW0K6kHTQsLIt4tLvJMYBksBf0wyspRX6KDWuP4ag7CB6sLQdfkyaUDUjhlsMXehNM4+2k968Lztb+5qRu/No8nm2FiErbyQoBVlHz9C9nFtPuXKD3NBecUQtAPifxzfCtYS26/8wDUq31UOMy3AoEne/ClDmxRhPbgh96xEonLem60P3Ql2T8AXt4InrCVJSh5CcqIyS4d6ZD8GI49MfKGRlldXy3ptpkPUaCGREPoNnk3Yp5u/BBM6Tz8Y4Y2xENhO+IlkvIDxzsXgsxI8UCuk7E5a38Hob8tHmtwxbifwdDJzOyQ8QK/00L0AZBQl098ml3U+xoGo0N/+hcqkjHh9R5lwf71/5113VXV9Kch/+Pfv6ZBG/twbjHGR3P0+0yiahRotqhSVqJPaiR4uabhP/EnrxD+lGf2MW1qTj/q/JKphncorQnKhk+A5EwPjAhMAkGBSsOAwIaBQAEFEdmL5mdMBmFmcNDtDP/eJwtobS+BBQKYhHh7k5r+SrmLuH8vpMYovFQjwIDAYag
  truststore.p12: MIIL/gIBAzCCC7cGCSqGSIb3DQEHAaCCC6gEggukMIILoDCCC5wGCSqGSIb3DQEHBqCCC40wgguJAgEAMIILggYJKoZIhvcNAQcBMCkGCiqGSIb3DQEMAQYwGwQUN4SYbJrNd6yvIycsn+eoQvGLxw8CAwDDUICCC0irU4VGWb2Am/3jk98HoiEKGApxZ4zzpnaqO0Owvq2OtZqWIygtz3pSKUs6GgOBuqQfb0tSBLglfN1GNXSxe8kNkUsjupsIkfSkU/3KMU2zeYytXCelrXTzdQ/bF4Fg3jmSatCZzOYIs3oj2GL8rYM9y3Vt5P+AIops3U0cjt6l8UTkKXAfhtwYtzRzZKraOaTjXsP/S6cftEf08SLY/SF6Uufx+v2/CI1uo9AGEQom6uaqsfcjlN4Clqj8gCynQMlWoTFOwjqDvB8tsJcEHVvCb5dWKqpa2m9u31XghurqQqG0rLPXdSrbgcDjv9kGT6MwtIXojKjSVcRb9ruBiIvz9o6tRYkkr91GW+Uxds4RfNlYcl1STAwEMdJcJov1Q0jIuJtL7Z4+cgtsvhRkMUQbVWI8ADgvcJPm/TPITWfv+M2Kv82X7xLTxCghK7zywoQRuW6IMwArqvVWT/S7CJ2wiGapL8iXsQyln1c0qkXTSTh13dhW+o+CLsfWNOkqGovy69nBaIm9SPXOmarpFjruQvGqcfdZzFtEGVmAqmMsfRyc1GvfrPR7S6r9Z+upZxp4fvchusXsUqnmVxkff3HGg59HqfeouwekfZGGfI40IDaYLVJaVyfj0VMtGl+hLaVlNoh8QXi0smJ04cFthdNSNSV12BXFjX3iJ/HxeaEF0bbd8r3kbWowzDGbtPkFjhuEsh0CJK4/kXjwHgoqt959isN4xUWmI5CwgMydVQWozsdsD+mgSWm9Le8nV/sQWdDWDh/PcyacsxkM+/zQ9oL17KqrchpJJB7a+Pg6PnTFpih6tZN5VyDcjm+ijoJoXu5h8iEUvlkfCLmfBuOjGY5FYu4F4Bziksf7updkanWd9qpkhKkNjFWpIgpiWWx8rbVLeZ1YmipiDUWsVx2/A1UUNg4DjpxRFgisAZY+fLcxjiCaF1kmjqz/lwy0YA7ByEfVgE0VpeTKaqIRdA8JB9X8sI3wxz55LObcV/bLbF5k5eBrGEXBsvFrE3aWD22/Zj4R95z69E7xPKzLNt7i3/ki6rfl1+IJdp1No5ewvxhBNqdZg+ToYpintPqdKU3CpAmdRE+iqNC51LCyENEXCo3SAxr9KjAmGmONVQ6WOcXsEa+Cqk8mWpOD/DBshhTHXHRmk4RK40qIWoxWbq0Z612e/ih8U0i68UgL8d8PwlrMbcsEv9xhpw1xsaY1lab7FPi/MRpMfx9pI3RalXffr8nLGFFfHHlQpWLrI58onpnbUrBXhUbxi9wPQh6RwCZTZvFhlqahbjZ2gbppqGOiS87fPRsumsKIlaSV32eqExQ/owxqbtlFZCb609GgHlDJzcQXurXt9SplZZW7ZnFxXYQOzTZAlShGzBhAgjntWrlIHlcM9fk702EZ3nC5M0OjRNVBlsOkj3me7PyXvU10LJbV+ZGXnpvo1cx0uV4tlSnzIpPBXjIj751Q5U90Esaav9fvf6w6simNdZ9Pj49LMfkRDqPZEQXRSnntqPzyLzbnBpQgUo0ptq8ydnStaWiVCMYiayzzRDkG6OORtN1MgOo5Q3uDYD3x2eedO0RtQp+ONb4O4Q5rNuIJbaBRIJ8iKc6/MwaaaYPRkl55ppj6NBNMzn3u2hHZbF7iKd0m5cZKrKVB5KaXOidAiFCP/6K3pkDbCMJCmtN3jId7P/2uN7QtZQUJE5bBkdqgsKU0UiJI6tKEckFXaz376SEJ/Hzqjw7MDsyE1t4EBxdUDa8+bvUO1bdNUdf2VveEtWtqREf5ZH6miFZ396P0p6h/GQ7N68BYl+a1B99ngA/d7JTwu2+Dn8G5e2dsUDZIyNE5yRKwPNLMEMBdBQliumn4yiEIogRYG0NGWGeSB/b7CWvYpXIdr2qEZ4kLxM/m6SmTYNcffFeFlmruXbqDGkTfe8KVTbeXQN5CvLC79+j7Sw/qCHgWtNmUBYRoveFe3yqKSboC86qP07EsHG0puC7fPyLEH3f3O0QZpEk2ZeJsAk8aa7Aw0USp6PUV/BjnT0wOFikHt1EGLql/MRyqi318UZYMTIn++OaP0cdZd6lh1foLnMr5sK9Tyb5zvB2W45A60WHTkzu6Ui/BwLPvsE12PO2ei6kXRG6PPzLV6dpyj/YkZmXGT+PnF+9ygGJdEfmiBPqalCbdoh3MB7cm+nFzSl7kuLvSa9yLwndiml/gSTHTVMjNDjgr9SvvhwG7uUYeR4vzqVVQfYY/WAIrkhcNxxxzHJtRzUiYiKs0JoKo9GFXALEDOmop0QltiUOec6joRLJ/8gDZHbQAFs0j04eFwt/c8Hbv2mDCL39vVqAzyDUZJsmrGvB4WkY3ll0xhOUe6T2lrQlPBw7P3J2vWlaQ9Y6jTo+9MiOLEznG6/GdBYTlh7LynasxoyFfW0tWuMkesfyeKVZrft8oTrgqtfo/ngsX8G0lr1hbZK8XHjTcHhuA0wO4i1ZActk1IGA50jwPCqO+qaxqbPNEub2S+QAJSPaOZGgEr6bgVfstA3lM9NPtPbtBjujmPdhbjeskkR/rI6RGnjcTENennj3qkf9BX2Ayq/fV4X/p3U7nlxOlitIr+XVYwRpes5WrNywbd/DJsjh2cKNUQjgiYq4F5TCAj35V9gYl+DS5+8x4pt/22HmJNx5d2cN9SnrhQVMDBRfjgGabz2RdqbDfb28amXt6w+BrIZ5eaGyJiAZ6gCaPy5IyOk38i04v0Chq2i58fRjQX9g3Jw5ZWv4jw93Q+2o3atTpsrM/+jLyd0Y7QKmnWaq1yoqXVJJ+DsJ3SLMLLbOMofgUX8snZb8Lbjv6ItA446c5xFWms3tvJUNjYYpI7lmXWCaPKt+11nm6Qz6yoPTWtao770NWbLhjnaPw3M28ACm9LwdoyPmRNrGJVhcQeH+LTEB/JN2khCr+I4zvniW8js3CaX4HO7Bi83dcuH9kh9HqOVp5I9l7wztC8xbu1u7Yrgsqu7MJDthfpNycwkkd1KmqFLGnwpPc3ZNvqpEwJZJAHjgXixj4pS/BwZTo8bK6d1WukQCUd50VvYmsVfbS7QyKIAHj++DxvlhdFHdQv7IhNZucZgoduh8LY3VBoSmVVGdrTch9Zlgb+ebvp8kOG5PiwOTcuWBB2RzZnCkIC1snCqRwkmJtuCHvdI9WaSu9GvFxy4mxETE71/hPV6gj4byjjk5G/oN1k6dRS1axXyagfLCezmZ7sbxbN1ILpZXAkqiv221Th+myl7AH9SeF9cIVT/kBWpBtFGMbiEVUQ8PRM3zXWmND1iunfD0XXMFpbaBwRIWPtKbs5Xm0kPXRuGWlvC/drCW/O6LdplMV2e9x16OlTQcSojG8JEMA7HxdX+eKt+9vD0hmbVD1a7PwNzqugouYVzR3F4hMjf2hBxqET7gxf02VJs2FaYyZzm9Q5br0I+6VeeU+0vOdP43VhFwbz6+5jAr2809ZrK18HmcYDWL9DGpvdiJd9qNiRkiY4NYUm7mXA2jUTxA8Fc8qkm13FlFcc9ctJ0gt1EHKZIKnCughy/fAhz2gE0zkqll2K4nunU2rpaSgU8kOrKno0LHwoGBHvLYmF1GaJotG7XKhUxWy+yXjz/yP3bntTmyd1DDuenHFFqxXpyqg1vCfmfnzvxsJtEpLwbCNALkE0XLD7fhak0U1VHWmHWJtT6/zQ901Dv+gVazK6/R5Z5mUt7L3UjGtNwrXF6+XjryuOvaspcOPvrI5mGoaAqRSZR/ydzhYlk+Me83m5pX/dWjyhr5Ubpm7KP0+zmbppXoi5DNoagB0dHlDvGPFklgwZAvviBQhbMNXD7PsuUO+F8+IMP0f8uTtTW2zk9Qse22yPjWD0+9YoSLRxTemwzA+MCEwCQYFKw4DAhoFAAQUrmuwur7d2rnTGdomddZ1q1a4luQEFFQJOOfeizbwnsXeRZsh7fTEJJ/8AgMBhqA=