{
 "title": "Oversight",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(up,job)" } },
   {
    "name": "node",
    "query": {
     "query": "label_values(up{job=~\"$job\"},node_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (node_name) (up{job=\"node\"})"
    }
   ]
  },
  {
   "title": "AMQ Artemis Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (up{job=\"amqbroker\"})"
    }
   ]
  },
  {
   "title": "Zookeeper Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (up{job=\"zookeeper\"})"
    }
   ]
  },
  {
   "title": "Kafka Broker Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (up{job=\"kafka\"})"
    }
   ]
  },
  {
   "title": "Camel Quarkus Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (up{job=\"camelquarkus\"})"
    }
   ]
  }
 ]
}